services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: tiny-web-app/app
    container_name: tiny_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./src:/var/www
      - ./docker/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - app-network

  nginx:
    image: nginx:1.21-alpine
    container_name: tiny_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - app

networks:
  app-network:
    driver: bridge